name: Publish Github Pages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/asciibook-action
        with:
          source: README.adoc
