name: Publish Github Pages

on:
  push:
    branchs:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      #- uses: ./
      #  with:
      #    source: README.adoc
      #  env:
      #    DEPLOY_TOKEN: ${{secrets.DEPLOY_TOKEN}}
      - name: Build and Publish
        run: |
          docker run -v $(pwd):/asciibook asciibook/asciibook ls
