name: Publish Github Pages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: asciibook/asciibook-action@master
        with:
          source: README.adoc
