name: Publish Github Pages

on:
  push:
    branchs:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          source: README.adoc
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
